INSERT INTO categories (category_id, name) VALUES
(1, 'RENT'),
(2, 'UTILITIES'),
(3, 'FOOD'),
(4, 'TRANSPORTATION'),
(5, 'EDUCATION'),
(6, 'CLOTHING'),
(7, 'HEALTHCARE'),
(8, 'HOUSEHOLD_SUPPLIES'),
(9, 'ENTERTAINMENT'),
(10, 'SPORTS'),
(11, 'GIFTS'),
(12, 'TRAVEL'),
(13, 'OTHERS');